### ISSUE TITLE
Analogue Pocket Any firmware - Game flickers when in Dock mode after starting

### ISSUE THREAD

**Issue by ncc1701p** [obsidian-dot-dev/openFPGA-MarioBros#1]
When in the Analogue Dock the game flickers constantly when playing. The game is normal at boot and all the way until the beginning demonstration. This effect does not occur when in hand-held mode. 

Core version 0.9.2
Analogue Pocket Firmware: Any
Analogue Dock Firmware: Any
[Genki Arcade - 406ffb73-3ca7-4d1c-8f18-69bb14cc62c7.webm](https://github.com/obsidian-dot-dev/openFPGA-MarioBros/assets/17013664/2fbb6063-12c3-4cda-a21a-7b40aa0ee49f)

Edit: I didnt realize this was an issue. please feel free to close

**Comment by obsidian-dot-dev** [comment]
Yes, this is a known issue, but I'll keep this ticket open to track a fix.

**Comment by obsidian-dot-dev** [comment]
Fixed in v0.9.3
